services:
  neo4j:
    image: neo4j:5.24
    container_name: neo4j-db
    environment:
      NEO4J_AUTH: neo4j/Str0ngPass!
      NEO4J_server_default__listen__address: 0.0.0.0
      NEO4J_server_default__advertised__address: neo4j
      NEO4J_PLUGINS: '["apoc"]'
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/var/lib/neo4j/bin/cypher-shell -u neo4j -p 'Str0ngPass!' -a bolt://localhost:7687 'RETURN 1;' || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 40s

  backend:
    build: ./backend
    environment:
      PORT: "3000"
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USERNAME: neo4j
      NEO4J_PASSWORD: Str0ngPass!
      AUTO_GENERATE_DATA: "true"
      GENERATE_MODE: demo
    ports:
      - "3000:3000"
    depends_on:
      neo4j:
        condition: service_healthy

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      backend:
        condition: service_started

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
